version: '2'

services:
  web:
    image: hojak/contao:4.4.0
    container_name: contao4-web
    ports:
      - "8080:80"
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - html_content:/var/www/html

  mysql:
    image: mysql:latest
    container_name: contao4-mysql
    volumes:
      - ./mysql_data/:/var/lib/mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contao
      MYSQL_USER: contao
      MYSQL_PASSWORD: contao

  phpmyadmin:
    image: nazarpc/phpmyadmin
    container_name: contao4-pma
    ports: 
      - "8888:80"
    links:
      - mysql
    depends_on:
      - mysql


volumes:
  html_content:

